version: '3.7'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - ATLAS_URI=mongodb://mongo:27017/water-company
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"